import:
  - ~/.config/alacritty/themes/dracula.yml
shell:
  program: /usr/bin/zsh
Font:
    normal:
        family: DroidSansMNerdFont-Regular
        style: Regular

    bold:
        family: DroidSansMNerdFont-Regular
        style: Bold

    italic:
        family: DroidSansMNerdFont-Regular
        style: Italic

    bold_italic:
        family: DroidSansMNerdFont-Regular
        style: Bold Italic

    book:
        family: DroidSansMNerdFont-Regular
        style: Book

    size: 11.0
window:
  padding:
    x: 30
    y: 30
  decorations: none
selection:
  save_to_clipboard: true
mouse_bindings:
  - { mouse: Right, action: Paste }
env:
  TERM: xterm-256color

