gui:
  theme:
    activeBorderColor:
      - '{color12}'
      - bold
    inactiveBorderColor:
      - '{cursor}'
    optionsTextColor:
      - '{color8}'
    selectedLineBgColor:
      - '{background}'
    cherryPickedCommitBgColor:
      - '{cursor}'
    cherryPickedCommitFgColor:
      - '{color4}'
    unstagedChangesColor:
      - '{color1}'
    defaultFgColor:
      - '{color7}'
    searchingActiveBorderColor:
      - '{color3}'

  authorColors:
    '*': '{color4}'
