#!/usr/bin/env bash

set -e

DEFAULT_CONFIG_PREFIX="default"
CONFIG_SUFFIX=".conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"

git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

configs=("${DEFAULT_CONFIG_PREFIX}" "$@")

for conf in "${configs[@]}"; do
  "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
    -v \
    -d "${BASEDIR}" \
    --plugin-dir dotbot-sudo \
    --plugin-dir dotbot-omnipkg \
    --plugin-dir dotbot-yum \
    --plugin-dir dotbot-yay \
    --plugin-dir dotbot-brew \
    -c "${conf}${CONFIG_SUFFIX}"
done
