colors:
  bg: "2b3339"
  bg0: "2b3339"
  bg1: "323c41"
  bg2: "3a454a"
  bg3: "445055"
  bg4: "4f5b58"

  fg: "d3c6aa"
  fg0: "fdf6e3"
  fg1: "d3c6aa"
  fg2: "c2b39e"
  fg3: "a7a09d"
  fg4: "8a9584"

  red: "e67e80"
  green: "a7c080"
  yellow: "dbbc7f"
  blue: "7fbbb3"
  purple: "d699b6"
  aqua: "83c092"
  orange: "e69875"
  gray: "868d80"

  alt_red: "f7a5a2"
  alt_green: "b8c29a"
  alt_yellow: "f0d799"
  alt_blue: "9ccfd8"
  alt_purple: "edc4d3"
  alt_aqua: "a3c9a5"
  alt_orange: "f2b493"
  alt_gray: "a3b3a2"

core:
  normal_text:
    foreground: fg
    background: bg

  regular_file:
    foreground: fg
    background: bg

  reset_to_normal: {}

  directory:
    foreground: blue

  symlink:
    foreground: alt_blue
    font-style: italic

  multi_hard_link:
    font-style: bold

  fifo:
    foreground: purple

  socket:
    foreground: purple
    font-style: bold

  door:
    foreground: alt_purple
    font-style: bold

  block_device:
    foreground: yellow
    font-style: bold

  character_device:
    foreground: alt_yellow
    font-style: italic

  broken_symlink:
    foreground: alt_red
    font-style: italic

  missing_symlink_target:
    foreground: fg
    background: alt_red

  setuid:
    foreground: fg
    background: red

  setgid:
    foreground: bg
    background: orange

  file_with_capability:
    foreground: bg
    background: red

  sticky_other_writable:
    foreground: fg
    background: blue
    font-style: italic

  other_writable:
    foreground: alt_green
    font-style: bold

  sticky:
    foreground: fg
    background: blue

  executable_file:
    foreground: alt_green
    font-style: bold

text:
  special:
    foreground: alt_yellow
    font-style: bold

  todo:
    foreground: alt_green

  licenses:
    foreground: fg1
    font-style: italic

  configuration:
    foreground: alt_yellow

  other:
    foreground: fg

markup:
  foreground: yellow

programming:
  source:
    foreground: green

  tooling:
    foreground: alt_green
    font-style: italic

    continuous-integration:
      foreground: alt_blue

media:
  foreground: aqua

  video:
    foreground: alt_aqua
    font-style: bold

office:
  foreground: alt_blue
  font-style: bold

archives:
  foreground: orange

  images:
    foreground: alt_orange
    font-style: bold

executable:
  foreground: alt_green
  font-style: bold

unimportant:
  foreground: bg3
  font-style: italic
