scheme: "Tokyo night dark"
author: "Michaël Ball"
base00: "16161E"
base01: "1A1B26"
base02: "2F3549"
base03: "444B6A"
base04: "787C99"
base05: "c0caf5"
base06: "CBCCD1"
base07: "D5D6DB"
base08: "F7768E" # red
base09: "FF9E64" # orange
base0A: "E0AF68" # yellow
base0B: "9ece6a" # green
base0C: "7DCFFF" # cyan
base0D: "7AA2F7" # blue
base0E: "BB9AF7" # purple
base0F: "73daca" # ?
