#! /usr/bin/env bash
mime=$(file -Lbs --mime-type "$1")
category=${mime%%/*}
kind=${mime##*/}
type=$(echo "$1" | grep -o '\.[^.]*$' | cut -d. -f2-)
ext=${1##*.}
if [ -d "$1" ]; then
  eza -l --git --color=always --icons --group-directories-first "$1"
elif [[ "$1" == *.md ]]; then
  glow -p -s $HOME/.cache/wal/colors-glow.json "$1"
elif [ "$category" = image ]; then
  fzf-preview.sh "$1"
  exiftool "$1" | bat --color=always -plyaml
elif [ "$kind" = json ]; then
  bat --color=always -l json "$1"
elif [ "$kind" = javascript ]; then
  bat --color=always -l js "$1"
elif [ "$ext" = lua ]; then
  bat --color=always -l lua "$1"
elif [ "$category" = text ]; then
  bat --color=always "$1"
else
  lesspipe.sh "$1" | bat --color=always
fi
