[nord]
button             = 5E81AC
button-active      = 81A1C1
button-disabled    = 434C5E
button-secondary   = D8DEE9
card               = 2E3440
main               = 2E3440
main-secondary     = 434c5e
misc               = FFFFFF
nav-active         = 4c566a
nav-active-text    = D8DEE9
notification       = 3b4252
notification-error = 3b4252
play-button        = 5E81AC
playback-bar       = DEDEDE
player             = 2E3440
shadow             = 1d2128
sidebar            = 2E3440
subtext            = E5E9F0
tab-active         = 3b4252
text               = D8DEE9

[dracula]
button             = 50fa7b
button-active      = 00bf76
button-disabled    = 3f3c45
button-secondary   = ff79c6
card               = 282a36
main               = 282a36
main-secondary     = 1c1e26
misc               = FFFFFF
nav-active         = 50fa7b
nav-active-text    = 282a36
notification       = 1c1e26
notification-error = 1c1e26
play-button        = 50fa7b
playback-bar       = 50fa7b
player             = 282a36
shadow             = 000000
sidebar            = 282a36
subtext            = bd93f9
tab-active         = 1c1e26
text               = 50fa7b

[rose-pine]
button             = ebbcba
button-active      = ebbcba
button-disabled    = 26233a
button-secondary   = 6e6a86
card               = 1f1d2e
main               = 191724
main-secondary     = 1f1d2e
misc               = FFFFFF
nav-active         = 1f1d2e
nav-active-text    = ebbcba
notification       = 26233a
notification-error = eb6f92
play-button        = ebbcba
playback-bar       = 6e6a86
player             = 191724
shadow             = 191724
sidebar            = 191724
subtext            = 908caa
tab-active         = 1f1d2e
text               = e0def4

[eldritch]
button             = 37f499
button-active      = 37f499
button-disabled    = 323449
button-secondary   = 04d1f9
card               = 212337
main               = 212337
main-secondary     = 323449
misc               = ebfafa
nav-active         = 37f499
nav-active-text    = 323449
notification       = 212337
notification-error = 212337
play-button        = 37f499
playback-bar       = 37f499
player             = 212337
shadow             = 212337
sidebar            = 212337
subtext            = 04d1f9
tab-active         = a48cf2
text               = 37f499

[catppuccin]
button             = a6e3a1
button-active      = f9e2af
button-disabled    = 181825
button-secondary   = 74c7ec
card               = 1e1e2e
main               = 11111b
main-secondary     = 1e1e2e
misc               = f4dbd6
nav-active         = 11111b
nav-active-text    = fab387 
notification       = 11111b
notification-error = 11111b
play-button        = ca9ee6
playback-bar       = dc8a78 
player             = 11111b
shadow             = 11111b
sidebar            = 11111b
subtext            = 7c7f93
tab-active         = 45475a
text               = cba6f7

[tokyo-night]
button             = 2ac3de
button-active      = 2ac3de
button-disabled    = a9b1d6
button-secondary   = a9b1d6
card               = 16161e
main               = 1a1b26
main-secondary     = 16161e
misc               = 000000
nav-active         = 27384e
nav-active-text    = 2ac3de
notification       = 414868
notification-error = ff0000
play-button        = a9b1d6
playback-bar       = 2ac3de
player             = 16161e
shadow             = 16161e
sidebar            = 16161e
subtext            = c0caf5
tab-active         = 27384e
text               = a9b1d6

[gruvbox]
button             = d5c4a1
button-active      = ebdbb2
button-disabled    = 353535
button-text        = 282828
card               = 282828
main               = 282828
main-secondary     = 353535
misc               = d5c4a1
notification       = 282828
notification-error = 282828
play-button        = d5c4a1
playback-bar       = d5c4a1
player             = 282828
selected-row       = 1d2021
shadow             = 282828
sidebar            = 282828
sidebar-button     = d5c4a1
sub-button         = d5c4a1
subbutton-text     = d5c4a1
subtext            = d5c4a1
tab-active         = 282828
text               = d5c4a1

[everforest]
button             = A7C080
button-active      = AEC984
button-disabled    = 374145
card               = 374145
heart              = A7C080
highlight          = 444747
highlight-elevated = 34393D
main               = 272E33
main-elevated      = 30363A
main-secondary     = 374145
main-transition    = 495156
misc               = 000000
notification       = 86AF87
notification-error = E67E80
pagelink-active    = 181C1E
play-button        = A7C080
play-button-active = AEC984
player             = 272E33
progress-bg        = 9DA9A0
progress-fg        = A7C080
radio-btn-active   = 86AF87
selected-row       = D3C6AA
shadow             = 374145
sidebar            = 2E383C
subtext            = 9AA79D
tab-active         = 181C1E
text               = D3C6AA 

; Description

; text             = main text, playlist names in main field, name of playlist selected in sidebar, headings
; subtext          = text in main buttons in sidebar, playlist names in sidebar, artist names, and mini infos
; nav-active-text  = text in main buttons in sidebar when active
; main             = main bg
; main-secondary   = bg color of selected song rows, bg color of artist/track cards
; sidebar          = sidebar bg
; player           = player bg
; card             = popup-card bg
; shadow           = all shadows
; button           = playlist buttons bg in sidebar, drop-down menus, now playing song, like button
; button-secondary = download and options button
; button-active    = hover on song selected
; button-disabled  = seekbar bg, volume bar bg, scrollbar
; nav-active       = sidebar buttons bg
; play-button      = color of main play button in main field
; tab-active       = button bg in main field (playlists, podcasts, artists, albums)
; notification     = notification ('Added to liked songs' etc.)
; playback-bar     = seekbar fg, volume bar fg, main play/pause button
; misc             = miscellaneous
