return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    highlight = { enable = true },
    indent = { enable = true },
    ensure_installed = {
      "bash",
      "comment",
      "css",
      "diff",
      "dockerfile",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "html",
      "hyprlang",
      "ini",
      "javascript",
      "json",
      "lua",
      "make",
      "markdown",
      "python",
      "rasi",
      "regex",
      "toml",
      "typescript",
      "vim",
      "vimdoc",
      "yaml",
    },
  },
  vim.treesitter.language.register("bash", "zsh"),
  vim.filetype.add({
    extension = { rasi = "rasi", rofi = "rasi" },
    filename = {},
    pattern = {
      [".*/waybar/config"] = "jsonc",
      [".*/kitty/.+%.conf"] = "bash",
      [".*/hypr/.+%.conf"] = "hyprlang",
      ["%.env%.[%w_.-]+"] = "sh",
    },
  }),
}
