# style name or JSON path (default "auto")
style: $HOME/.config/glow/colors.json
# mouse support (TUI-mode only)
mouse: false
# use pager to display markdown
pager: less
# word-wrap at width
width: 80
