# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/refs/heads/master/schema/config.json
gui:
  theme:
    selectedLineBgColor:
      - blue
    inactiveViewSelectedLineBgColor:
      - bold
  spinner:
    frames:
      - "|"
      - /
      - "-"
      - \
    rate: 50
git:
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never --width={{columnWidth}}
keybinding:
  universal:
    redo: <c-z>
    confirmInEditor: <a-enter>
