sed -i 's/POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND=255/POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND=244/g' ~/.p10k.zsh
sed -i 's/POWERLEVEL9K_OS_ICON_FOREGROUND=232/POWERLEVEL9K_OS_ICON_FOREGROUND=255/g' ~/.p10k.zsh
sed -i 's/POWERLEVEL9K_OS_ICON_BACKGROUND=7/POWERLEVEL9K_OS_ICON_BACKGROUND=67/g' ~/.p10k.zsh
sed -i 's/POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=76/POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=84/g' ~/.p10k.zsh
sed -i 's/POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=250/POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=0/g' ~/.p10k.zsh
sed -i 's/POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=255/POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=0/g' ~/.p10k.zsh
sed -i 's/POWERLEVEL9K_STATUS_OK_BACKGROUND=0/POWERLEVEL9K_STATUS_OK_BACKGROUND=235/g' ~/.p10k.zsh
sed -i 's/POWERLEVEL9K_STATUS_OK_PIPE_BACKGROUND=0/POWERLEVEL9K_STATUS_OK_PIPE_BACKGROUND=235/g' ~/.p10k.zsh
