#!/usr/bin/zsh
#zmodload zsh/zprof
source $HOME/.aliases.zsh
source $HOME/.env
source $HOME/.zshkeybindings.zsh

PATH="${PATH}:$HOME/bin:$HOME/.local/bin:$HOME/.krew/bin:$HOME/.npm-global/bin:$HOME/.nix-profile/bin"
export PATH

# [[ -r ~/git/znap/znap/znap.zsh ]] ||
#     git clone --depth 1 -- \
#         https://github.com/marlonrichert/zsh-snap.git ~/git/znap/znap
source ~/git/znap/znap/znap.zsh # Start Znap
znap source ohmyzsh/ohmyzsh plugins/{dirhistory,gitfast}
#znap source romkatv/powerlevel10k
znap source MichaelAquilina/zsh-you-should-use
znap source ajeetdsouza/zoxide
#znap source Freed-Wu/fzf-tab-source
znap source Aloxaf/fzf-tab
znap install zsh-users/zsh-completions
znap source zsh-users/zsh-autosuggestions
znap source zdharma-continuum/fast-syntax-highlighting
znap source zsh-users/zsh-history-substring-search
znap source jeffreytse/zsh-vi-mode

# Ensure up and down arrow works for searching history
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# fzf stuff
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh
#source $HOME/.cache/wal/colors-fzf.sh
source $HOME/.config/flavours/fzf.sh

# Make autocomplete work with sshpass aliases
compdef _ssh_hosts sshpass s sr
compdef _kubectl kubecolor
# Make autocomplete work for the jctl() function
compdef _journalctl jctl
# Sourcing k8s related stuff if using k8s
#if command -v kubectl &> /dev/null
#then
#    source $HOME/.functions_k8s
#fi

znap eval oh-my-posh 'oh-my-posh init zsh --config $HOME/.config/oh-my-posh/omp.yaml'
source $HOME/.zshenv.zsh
source $HOME/.zstyle.zsh

# Change cursor shape for different vi modes.
function zle-keymap-select {
  if [[ ${KEYMAP} == vicmd ]] ||
    [[ $1 = 'block' ]]; then
    echo -ne '\e[1 q'
  elif [[ ${KEYMAP} == main ]] ||
    [[ ${KEYMAP} == viins ]] ||
    [[ ${KEYMAP} = '' ]] ||
    [[ $1 = 'beam' ]]; then
    echo -ne '\e[5 q'
  fi
}
zle -N zle-keymap-select
zle-line-init() {
  zle -K viins # initiate `vi insert` as keymap (can be removed if `bindkey -V` has been set elsewhere)
  echo -ne "\e[5 q"
}
zle -N zle-line-init
echo -ne '\e[5 q'                # Use beam shape cursor on startup.
preexec() { echo -ne '\e[5 q'; } # Use beam shape cursor for each new prompt.

znap prompt
# pnpm end
#zprof
