#zmodload zsh/zprof
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source $HOME/.aliases
source $HOME/.env
source $HOME/.zstyle

PATH="${PATH}:$HOME/.local/bin:$HOME/bin"; export PATH;

#FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

source $HOME/.antidote/antidote.zsh
antidote load

autoload -Uz compinit
ZSH_COMPDUMP=${ZSH_COMPDUMP:-${ZDOTDIR:-~}/.zcompdump}

# cache .zcompdump for about a day
if [[ $ZSH_COMPDUMP(#qNmh-20) ]]; then
  compinit -C -d "$ZSH_COMPDUMP"
else
  compinit -i -d "$ZSH_COMPDUMP"; touch "$ZSH_COMPDUMP"
fi
{
  # compile .zcompdump
  if [[ -s "$ZSH_COMPDUMP" && (! -s "${ZSH_COMPDUMP}.zwc" || "$ZSH_COMPDUMP" -nt "${ZSH_COMPDUMP}.zwc") ]]; then
    zcompile "$ZSH_COMPDUMP"
  fi
} &!

# Ensure up and down arrow works for searching history
#bindkey '^[[A' history-substring-search-up
bindkey '^[OA' history-substring-search-up
#bindkey '^[[B' history-substring-search-down
bindkey '^[OB' history-substring-search-down

# Ensuring that autocomplete works with sshpass aliases
compdef _ssh_hosts sshpass s sr
# Sourcing k8s related stuff if using k8s
if command -v kubectl &> /dev/null
then
    source $HOME/.functions_k8s
fi

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
source $HOME/.zshenv
