k9s:
  liveViewAutoRefresh: false
  screenDumpDir: /tmp/dumps
  refreshRate: 2
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: false
  ui:
    enableMouse: false
    headless: false
    logoless: false
    crumbsless: false
    noIcons: false
    reactive: false
    skin: colors
    defaultsToFullScreen: false
  noIcons: false
  skipLatestRevCheck: false
  keepMissingClusters: false
  logger:
    tail: 200
    buffer: 500
    sinceSeconds: 300 # => tail the last 5 mins.
    textWrap: false
    showTime: false
  shellPod:
    image: killerAdmin
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
    tty: true
